# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Stelfox
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog where I am keeping track on my data visualisation journey. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://davidstelfox.github.io" # the base hostname & protocol for your site
twitter_username: stelfad
github_username:  davidstelfox


# Build settings
markdown: kramdown
